### ISSUE TITLE
structuremap.3.1.5.154: scanner.AddAllTypesOf -> FindAllTypesFilter -> Does not filter out non concrete types and leads to 'Only concrete types can be built by ConstructorInstance'

### ISSUE THREAD

**Issue by J-ohn** [structuremap/structuremap#338] opened 2015-04-28 19:07 UTC
Repro:

public abstract class ParentClass{
}

public class ChildClass : ParentClass{
}

container.AddAllTypesOf<ParentClass>();

container.GetAllInstances<ParentClass>(); -> Boom Only concrete types can be built by ConstructorInstance

Workaround:

Write your own custom filter:

 public class FindAllTypesFilter : IRegistrationConvention
    {
        private StructureMap.Graph.FindAllTypesFilter innerFilter;

        public FindAllTypesFilter(Type pluginType)
        {
            innerFilter = new StructureMap.Graph.FindAllTypesFilter(pluginType);
        }

        public void Process(Type type, Registry registry)
        {
            if (!type.IsConcrete())
            {
                return;
            }

            innerFilter.Process(type, registry);
        }

    }

And instead of AddAllTypesOf
use
 scanner.With(new My.FindAllTypesFilter(typeof(ParentClass)));

Got structuremap from nuget:

packages\structuremap.3.1.5.154\lib\net40\StructureMap.dll

Thanks!

**Comment by jeremydmiller** [comment] 2015-05-01 18:02
Got it, but I'm not sure when I'll be able to address it. Soon, since you've done most of the work already;)

**Comment by J-ohn** [comment] 2015-06-04 12:09
Thanks dude, really appreciate it!

**Comment by jeremydmiller** [comment] 2015-07-02 21:09
@J-ohn Can you retry this with either 3.1.5 or better yet, master? I could not reproduce this locally. There is a Bug_338 test in the code now. Maybe see if I got the repro steps wrong?

**Comment by J-ohn** [comment] 2015-07-02 23:12
Will do tomorrow.

-----Original Message-----

**Comment by J-ohn** [comment] 2015-07-14 06:28
I have written what I though to be the repro case but you are right, I can not reproduce in a clean environment. The project I encountered this in is rather big and was upgraded from Structuremap 2.xx so it might be that I have something specific there thats causing it. I will investigate and let you know.

**Comment by J-ohn** [comment] 2015-09-15 18:27
Jeremy, I looked further into this. This is roughly what we are doing:

      class Program
    {
        static void Main(string[] args)
        {
            var container = new StructureMap.Container();

            container.Configure(c =>
            {
                c.Scan(s =>
                {
                    s.LookForRegistries();
                    s.AssembliesFromApplicationBaseDirectory();
                });
            });

            foreach (var item in container.GetAllInstances<MyAbstractThingie>())
            {
                item.Do();
            }

            Console.ReadLine();

            var thingie = container.GetInstance<MyAbstractThingie>("MyConcreteThingie");

            thingie.Do();

            Console.ReadLine();
        }
    }

    public class MyRegistry : Registry
    {
        public MyRegistry()
        {
            Scan((s) =>
            {
                s.AddAllTypesOf<MyAbstractThingie>().NameBy(x => x.Name);
                s.AssembliesFromApplicationBaseDirectory();
            });
        }
    }

    public abstract class MyAbstractThingie
    {
        public abstract void Do();
    }

    public class MyConcreteThingie : MyAbstractThingie
    {

        public override void Do()
        {
            Console.WriteLine(this.GetType().Name);
        }
    }

Still wont behave in the same manner in the console as it does on the site. Exception information:

[ArgumentOutOfRangeException: Only concrete types can be built by ConstructorInstance
Parameter name: concreteType]
   StructureMap.Pipeline.ConstructorInstance`1..ctor(Type concreteType) in c:\BuildAgent\work\a395dbde6b793293\src\StructureMap\Pipeline\ConstructorInstance.cs:44
   StructureMap.Graph.PluginFamily.AddType(Type concreteType, String name) in c:\BuildAgent\work\a395dbde6b793293\src\StructureMap\Graph\PluginFamily.cs:270
   StructureMap.StringExtensions.Each(IEnumerable`1 enumerable, Action`1 action) in c:\BuildAgent\work\a395dbde6b793293\src\StructureMap\Extensions.cs:12
   StructureMap.Configuration.DSL.Registry.StructureMap.Configuration.IPluginGraphConfiguration.Configure(PluginGraph graph) in c:\BuildAgent\work\a395dbde6b793293\src\StructureMap\Configuration\DSL\Registry.cs:235
   StructureMap.Graph.AssemblyScanner.ScanForTypes(TypePool types, PluginGraph pluginGraph) in c:\BuildAgent\work\a395dbde6b793293\src\StructureMap\Graph\AssemblyScanner.cs:131
   StructureMap.StringExtensions.Each(IEnumerable`1 enumerable, Action`1 action) in c:\BuildAgent\work\a395dbde6b793293\src\StructureMap\Extensions.cs:12
   StructureMap.PluginGraphBuilder.RunConfigurations() in c:\BuildAgent\work\a395dbde6b793293\src\StructureMap\PluginGraphBuilder.cs:85
   StructureMap.PluginGraphBuilder.Build() in c:\BuildAgent\work\a395dbde6b793293\src\StructureMap\PluginGraphBuilder.cs:47
   StructureMap.PipelineGraph.Configure(Action`1 configure) in c:\BuildAgent\work\a395dbde6b793293\src\StructureMap\PipelineGraph.cs:168
   StructureMap.Container.Configure(Action`1 configure) in c:\BuildAgent\work\a395dbde6b793293\src\StructureMap\Container.cs:388
   Netvolution.Web.ApplicationSetup.Configure(IContainer container) in c:\Netvolution.Net\netvolutionNet Dev\netvolution.NET\Netvolution\Web\ApplicationSetup.cs:60
   Netvolution.Web.ApplicationSetup.Load() in c:\Netvolution.Net\netvolutionNet Dev\netvolution.NET\Netvolution\Web\ApplicationSetup.cs:211
   Netvolution.Web.ApplicationSetup.Startup() in c:\Netvolution.Net\netvolutionNet Dev\netvolution.NET\Netvolution\Web\ApplicationSetup.cs:270
   netvolutionNet.Global.Application_Start(Object sender, EventArgs e) in c:\Netvolution.Net\netvolutionNet Dev\netvolution.NET\netvolution.NET\Global.asax.cs:124

[HttpException (0x80004005): Only concrete types can be built by ConstructorInstance
Parameter name: concreteType]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +12601645
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +175
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +304
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +404
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +475

[HttpException (0x80004005): Only concrete types can be built by ConstructorInstance
Parameter name: concreteType]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +12618692
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +159
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +12458309

If I comment in the filter part (thats the custom one I already posted), and comment out .AddAllTypesOf<ExtendedControlBase>()  it works just fine:

Scan(scanner =>
            {
                //var filter = new FindAllTypesFilter(typeof(ExtendedControlBase));
                //filter.NameBy(x => x.FullName);
                //scanner.With(filter);
                scanner.AddAllTypesOf<ExtendedControlBase>().NameBy(x => x.FullName);
                scanner.AddAllTypesOf<IRequestContextInterceptor>();
                scanner.AssembliesFromApplicationBaseDirectory();
            }); 

Can you point me to a direction for further investigation?

Thanks in advance 
John

**Comment by jeremydmiller** [comment] 2015-09-22 01:28
@J-ohn Can I get you to try this with the latest SM 3.2 alpha maybe? I put a change in on July 2nd that **should** address this.

**Comment by jeremydmiller** [comment] 2015-10-09 20:38
Closing for now.

**Closed by jeremydmiller** 2015-10-09 20:38 UTC
Labels: Bug, Cannot Reproduce, Need more information
