### ISSUE TITLE
GetAllInstances is failing with ExplicitArguments

### ISSUE THREAD

**Issue by DixonD-git** [structuremap/structuremap#413] opened 2015-10-18 18:47 UTC
Lets have `IDummyService` and a couple of its implementations:
```
public interface IDummyService
{
	string Name { get; set; }
}

public class DummyService : IDummyService
{
	public string Name { get; set; }
}

public class DummyServiceWithName : IDummyService
{
	public DummyServiceWithName(string namePart1, string namePart2)
	{
		Name = string.Format("{0} {1}", namePart1, namePart2);
	}

	public string Name { get; set; }
}

public class DummyServiceWithReversedName : IDummyService
{
	public DummyServiceWithReversedName(string namePart1, string namePart2)
	{
		Name = string.Format("{0} {1}", namePart2, namePart1);
	}

	public string Name { get; set; }
}
```
Then `Container.GetAllInstances<IDummyService>` is failing with `ExplicitArguments` specified:
```
[Test]
public void TryToResolveCollectionWithExplicitArgs()
{
	var container = new Container();

	container.Configure(cfg =>
	{
		cfg.For<IDummyService>().Use<DummyService>();
		cfg.For<IDummyService>().Add<DummyServiceWithName>().Named("direct");
		cfg.For<IDummyService>().Add<DummyServiceWithReversedName>().Named("reversed");
	});

	var explicitArgs = new ExplicitArguments();
	explicitArgs.SetArg("namePart1", "John");
	explicitArgs.SetArg("namePart2", "Smith");

	// this one is failing
	container.GetAllInstances<IDummyService>(explicitArgs);

	// this one is failing as well
	container.GetInstance<IList<IDummyService>>(explicitArgs);
}
```
Am I doing anything wrong?

**Comment by jeremydmiller** [comment] 2015-10-19 13:52
@DixonD-git You're bumping into an old limitation. If you use ExplicitArguments with primitive arguments (strings, numbers, dates, enumerations), it can only apply to the very top level `Instance`. Non-primitives work fine because that's done by sticking them into the IBuildSession defaults, but primitives have to be applied at each individual Instance.

**Comment by DixonD-git** [comment] 2015-10-19 13:57
@jeremydmiller Is it by design or something that needs be fixed eventually?

**Comment by jeremydmiller** [comment] 2015-10-19 14:02
@DixonD-git "by design" gives me way too much credit. When this has come up before I've been fine with keeping this limitation. I'd be worried about adding yet more if/then logic in the construction pipeline, but if we could do it efficiently, I'd be okay with addressing this some day

**Comment by jeremydmiller** [comment] 2015-11-13 12:06
@DixonD-git I'm going to update the documentation on this to call out the limitation and maybe even write up a work around for it. I'm closing this just as book-keeping.

**Closed by jeremydmiller** 2015-11-13 12:06 UTC
